In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,accuracy_score
import mlflow
from mlflow.models import infer_signature

In [17]:
# set the tracking uri
mlflow.set_tracking_uri(uri="http://localhost:5000")



In [18]:
## load the dataset
X,y = datasets.load_iris(return_X_y=True)
## split the data  into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## define the model parameters
params = {
    'penalty': 'l2',
    'dual': False,
    'tol': 0.0001,
    'C': 1.0,
    'fit_intercept': True,
    'intercept_scaling': 1,
    'class_weight': None,
    'random_state': None,
    'solver': 'lbfgs',
    'max_iter': 1000,
    'multi_class': 'deprecated',
    'verbose': 0,
    'warm_start': False,
    'n_jobs': None,
    'l1_ratio': None
}

# train the model
log_reg = LogisticRegression(**params)
log_reg.fit(X_train, y_train)



LogisticRegression(max_iter=1000)

In [19]:
## prediction 

y_pred = log_reg.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [20]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 1.0


In [26]:
## MLFLOW tracking
#create an experiment
mlflow.set_experiment("Iris_Classification")

#start an MLflow run
with mlflow.start_run():
    #log the hyperparameters
    mlflow.log_params(params)
    #log the accuracy metric
    mlflow.log_metric("accuracy", accuracy)

    #set a tag
    mlflow.set_tags({"model": "LogisticRegression", "dataset": "Iris"})

    # infer the model signature
    # Input signature is the schema that defines the expected format, shape, and type of the input data and the output predictions of a model.
    signature = infer_signature(X_train, y_pred)
    #log the model
    model_info = mlflow.sklearn.log_model(sk_model=log_reg,
                                          artifact_path="iris_model",
                                          signature=signature,
                                          input_example=X_train,
                                          registered_model_name="Iris_LogisticRegression_Model")



2025/07/15 13:10:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Registered model 'Iris_LogisticRegression_Model' already exists. Creating a new version of this model...
2025/07/15 13:11:00 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Iris_LogisticRegression_Model, version 2


🏃 View run amusing-bug-673 at: http://localhost:5000/#/experiments/595335853033740055/runs/fcb8ca0cf00e4e44ba8cf0c74bbe775c
🧪 View experiment at: http://localhost:5000/#/experiments/595335853033740055


Created version '2' of model 'Iris_LogisticRegression_Model'.


In [22]:

## define the model parameters
params = {
    'dual': False,
    'tol': 0.0001,
    'C': 1.0,
    'fit_intercept': True,
    'intercept_scaling': 1,
    'class_weight': None,
    'random_state': None,
    'solver': 'newton-cg',
    'max_iter': 100,
    'multi_class': 'deprecated',
    'verbose': 0,
    'warm_start': False,
    'n_jobs': None,
    'l1_ratio': None
}

# train the model
log_reg = LogisticRegression(**params)
log_reg.fit(X_train, y_train)



LogisticRegression(solver='newton-cg')

In [23]:
y_pred = log_reg.predict(X_test)

In [24]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [25]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 1.0


In [27]:
model_info.model_uri

'models:/m-4847254fc3de42728a4a5a7c9cebd703'

In [32]:
from mlflow.models import validate_serving_input

model_uri = model_info.model_uri

# The model is logged with an input example. MLflow converts
# it into the serving payload format for the deployed model endpoint,
# and saves it to 'serving_input_payload.json'
serving_payload = """{
  "inputs": [
    [
      4.6,
      3.6,
      1.0,
      0.2
    ],
    [
      5.7,
      4.4,
      1.5,
      0.4
    ],
    [
      6.7,
      3.1,
      4.4,
      1.4
    ],
    [
      4.8,
      3.4,
      1.6,
      0.2
    ],
    [
      4.4,
      3.2,
      1.3,
      0.2
    ],
    [
      6.3,
      2.5,
      5.0,
      1.9
    ],
    [
      6.4,
      3.2,
      4.5,
      1.5
    ],
    [
      5.2,
      3.5,
      1.5,
      0.2
    ],
    [
      5.0,
      3.6,
      1.4,
      0.2
    ],
    [
      5.2,
      4.1,
      1.5,
      0.1
    ],
    [
      5.8,
      2.7,
      5.1,
      1.9
    ],
    [
      6.0,
      3.4,
      4.5,
      1.6
    ],
    [
      6.7,
      3.1,
      4.7,
      1.5
    ],
    [
      5.4,
      3.9,
      1.3,
      0.4
    ],
    [
      5.4,
      3.7,
      1.5,
      0.2
    ],
    [
      5.5,
      2.4,
      3.7,
      1.0
    ],
    [
      6.3,
      2.8,
      5.1,
      1.5
    ],
    [
      6.4,
      3.1,
      5.5,
      1.8
    ],
    [
      6.6,
      3.0,
      4.4,
      1.4
    ],
    [
      7.2,
      3.6,
      6.1,
      2.5
    ],
    [
      5.7,
      2.9,
      4.2,
      1.3
    ],
    [
      7.6,
      3.0,
      6.6,
      2.1
    ],
    [
      5.6,
      3.0,
      4.5,
      1.5
    ],
    [
      5.1,
      3.5,
      1.4,
      0.2
    ],
    [
      7.7,
      2.8,
      6.7,
      2.0
    ],
    [
      5.8,
      2.7,
      4.1,
      1.0
    ],
    [
      5.2,
      3.4,
      1.4,
      0.2
    ],
    [
      5.0,
      3.5,
      1.3,
      0.3
    ],
    [
      5.1,
      3.8,
      1.9,
      0.4
    ],
    [
      5.0,
      2.0,
      3.5,
      1.0
    ],
    [
      6.3,
      2.7,
      4.9,
      1.8
    ],
    [
      4.8,
      3.4,
      1.9,
      0.2
    ],
    [
      5.0,
      3.0,
      1.6,
      0.2
    ],
    [
      5.1,
      3.3,
      1.7,
      0.5
    ],
    [
      5.6,
      2.7,
      4.2,
      1.3
    ],
    [
      5.1,
      3.4,
      1.5,
      0.2
    ],
    [
      5.7,
      3.0,
      4.2,
      1.2
    ],
    [
      7.7,
      3.8,
      6.7,
      2.2
    ],
    [
      4.6,
      3.2,
      1.4,
      0.2
    ],
    [
      6.2,
      2.9,
      4.3,
      1.3
    ],
    [
      5.7,
      2.5,
      5.0,
      2.0
    ],
    [
      5.5,
      4.2,
      1.4,
      0.2
    ],
    [
      6.0,
      3.0,
      4.8,
      1.8
    ],
    [
      5.8,
      2.7,
      5.1,
      1.9
    ],
    [
      6.0,
      2.2,
      4.0,
      1.0
    ],
    [
      5.4,
      3.0,
      4.5,
      1.5
    ],
    [
      6.2,
      3.4,
      5.4,
      2.3
    ],
    [
      5.5,
      2.3,
      4.0,
      1.3
    ],
    [
      5.4,
      3.9,
      1.7,
      0.4
    ],
    [
      5.0,
      2.3,
      3.3,
      1.0
    ],
    [
      6.4,
      2.7,
      5.3,
      1.9
    ],
    [
      5.0,
      3.3,
      1.4,
      0.2
    ],
    [
      5.0,
      3.2,
      1.2,
      0.2
    ],
    [
      5.5,
      2.4,
      3.8,
      1.1
    ],
    [
      6.7,
      3.0,
      5.0,
      1.7
    ],
    [
      4.9,
      3.1,
      1.5,
      0.2
    ],
    [
      5.8,
      2.8,
      5.1,
      2.4
    ],
    [
      5.0,
      3.4,
      1.5,
      0.2
    ],
    [
      5.0,
      3.5,
      1.6,
      0.6
    ],
    [
      5.9,
      3.2,
      4.8,
      1.8
    ],
    [
      5.1,
      2.5,
      3.0,
      1.1
    ],
    [
      6.9,
      3.2,
      5.7,
      2.3
    ],
    [
      6.0,
      2.7,
      5.1,
      1.6
    ],
    [
      6.1,
      2.6,
      5.6,
      1.4
    ],
    [
      7.7,
      3.0,
      6.1,
      2.3
    ],
    [
      5.5,
      2.5,
      4.0,
      1.3
    ],
    [
      4.4,
      2.9,
      1.4,
      0.2
    ],
    [
      4.3,
      3.0,
      1.1,
      0.1
    ],
    [
      6.0,
      2.2,
      5.0,
      1.5
    ],
    [
      7.2,
      3.2,
      6.0,
      1.8
    ],
    [
      4.6,
      3.1,
      1.5,
      0.2
    ],
    [
      5.1,
      3.5,
      1.4,
      0.3
    ],
    [
      4.4,
      3.0,
      1.3,
      0.2
    ],
    [
      6.3,
      2.5,
      4.9,
      1.5
    ],
    [
      6.3,
      3.4,
      5.6,
      2.4
    ],
    [
      4.6,
      3.4,
      1.4,
      0.3
    ],
    [
      6.8,
      3.0,
      5.5,
      2.1
    ],
    [
      6.3,
      3.3,
      6.0,
      2.5
    ],
    [
      4.7,
      3.2,
      1.3,
      0.2
    ],
    [
      6.1,
      2.9,
      4.7,
      1.4
    ],
    [
      6.5,
      2.8,
      4.6,
      1.5
    ],
    [
      6.2,
      2.8,
      4.8,
      1.8
    ],
    [
      7.0,
      3.2,
      4.7,
      1.4
    ],
    [
      6.4,
      3.2,
      5.3,
      2.3
    ],
    [
      5.1,
      3.8,
      1.6,
      0.2
    ],
    [
      6.9,
      3.1,
      5.4,
      2.1
    ],
    [
      5.9,
      3.0,
      4.2,
      1.5
    ],
    [
      6.5,
      3.0,
      5.2,
      2.0
    ],
    [
      5.7,
      2.6,
      3.5,
      1.0
    ],
    [
      5.2,
      2.7,
      3.9,
      1.4
    ],
    [
      6.1,
      3.0,
      4.6,
      1.4
    ],
    [
      4.5,
      2.3,
      1.3,
      0.3
    ],
    [
      6.6,
      2.9,
      4.6,
      1.3
    ],
    [
      5.5,
      2.6,
      4.4,
      1.2
    ],
    [
      5.3,
      3.7,
      1.5,
      0.2
    ],
    [
      5.6,
      3.0,
      4.1,
      1.3
    ],
    [
      7.3,
      2.9,
      6.3,
      1.8
    ],
    [
      6.7,
      3.3,
      5.7,
      2.1
    ],
    [
      5.1,
      3.7,
      1.5,
      0.4
    ],
    [
      4.9,
      2.4,
      3.3,
      1.0
    ],
    [
      6.7,
      3.3,
      5.7,
      2.5
    ],
    [
      7.2,
      3.0,
      5.8,
      1.6
    ],
    [
      4.9,
      3.6,
      1.4,
      0.1
    ],
    [
      6.7,
      3.1,
      5.6,
      2.4
    ],
    [
      4.9,
      3.0,
      1.4,
      0.2
    ],
    [
      6.9,
      3.1,
      4.9,
      1.5
    ],
    [
      7.4,
      2.8,
      6.1,
      1.9
    ],
    [
      6.3,
      2.9,
      5.6,
      1.8
    ],
    [
      5.7,
      2.8,
      4.1,
      1.3
    ],
    [
      6.5,
      3.0,
      5.5,
      1.8
    ],
    [
      6.3,
      2.3,
      4.4,
      1.3
    ],
    [
      6.4,
      2.9,
      4.3,
      1.3
    ],
    [
      5.6,
      2.8,
      4.9,
      2.0
    ],
    [
      5.9,
      3.0,
      5.1,
      1.8
    ],
    [
      5.4,
      3.4,
      1.7,
      0.2
    ],
    [
      6.1,
      2.8,
      4.0,
      1.3
    ],
    [
      4.9,
      2.5,
      4.5,
      1.7
    ],
    [
      5.8,
      4.0,
      1.2,
      0.2
    ],
    [
      5.8,
      2.6,
      4.0,
      1.2
    ],
    [
      7.1,
      3.0,
      5.9,
      2.1
    ]
  ]
}
   """

# Validate the serving payload works on the model
validate_serving_input(model_uri, serving_payload)

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [33]:
### load the model back for prediction as a generic python function model

loaded_model = mlflow.pyfunc.load_model(model_uri)
predictions = loaded_model.predict(X_test)

iris_features_name = datasets.load_iris().feature_names
result = pd.DataFrame(X_test, columns=iris_features_name)
result["actual_label"] = y_test
result["predicted_label"] = predictions


In [34]:
result

sepal length (cm)  sepal width (cm)  ...  actual_label  predicted_label
0                 6.1               2.8  ...             1                1
1                 5.7               3.8  ...             0                0
2                 7.7               2.6  ...             2                2
3                 6.0               2.9  ...             1                1
4                 6.8               2.8  ...             1                1
5                 5.4               3.4  ...             0                0
6                 5.6               2.9  ...             1                1
7                 6.9               3.1  ...             2                2
8                 6.2               2.2  ...             1                1
9                 5.8               2.7  ...             1                1
10                6.5               3.2  ...             2                2
11                4.8               3.0  ...             0                0
12                5.5               3.5  ...             0                0
13                4.9               3.1  ...             0                0
14                5.1               3.8  ...             0                0
15                6.3               3.3  ...             1                1
16                6.5               3.0  ...             2                2
17                5.6               2.5  ...             1                1
18                5.7               2.8  ...             1                1
19                6.4               2.8  ...             2                2
20                4.7               3.2  ...             0                0
21                6.1               3.0  ...             2                2
22                5.0               3.4  ...             0                0
23                6.4               2.8  ...             2                2
24                7.9               3.8  ...             2                2
25                6.7               3.0  ...             2                2
26                6.7               2.5  ...             2                2
27                6.8               3.2  ...             2                2
28                4.8               3.0  ...             0                0
29                4.8               3.1  ...             0                0

[30 rows x 6 columns]

In [35]:
result[:5]

sepal length (cm)  sepal width (cm)  ...  actual_label  predicted_label
0                6.1               2.8  ...             1                1
1                5.7               3.8  ...             0                0
2                7.7               2.6  ...             2                2
3                6.0               2.9  ...             1                1
4                6.8               2.8  ...             1                1

[5 rows x 6 columns]

In [36]:
# model registry - is a central repository for managing and storing machine learning models. It provides a way to organize, version, and track models throughout their lifecycle, from development to deployment. The model registry allows data scientists and ML engineers to collaborate effectively, ensuring that the right models are used in production environments while maintaining a history of changes and performance metrics.

#iam not registering the model first i have to validate the model and then register it

mlflow.set_experiment("Iris_Classification")

#start an MLflow run
with mlflow.start_run():
    #log the hyperparameters
    mlflow.log_params(params)
    #log the accuracy metric
    mlflow.log_metric("accuracy", accuracy)

    #set a tag
    mlflow.set_tags({"model": "LogisticRegression", "dataset": "Iris"})

    # infer the model signature
    # Input signature is the schema that defines the expected format, shape, and type of the input data and the output predictions of a model.
    signature = infer_signature(X_train, y_pred)
    #log the model
    model_info = mlflow.sklearn.log_model(sk_model=log_reg,
                                          artifact_path="iris_model",
                                          signature=signature,
                                          input_example=X_train)
                                            # registered_model_name="Iris_LogisticRegression_Model") # not registering the model    




2025/07/15 15:40:26 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.


🏃 View run stylish-duck-448 at: http://localhost:5000/#/experiments/595335853033740055/runs/4f1e15eabe5b44d2b710056e58549135
🧪 View experiment at: http://localhost:5000/#/experiments/595335853033740055


In [37]:

## Inferencing from model registry

model_name = "Iris_LogisticRegression_Model"
model_version ="latest"

model_uri = f"models:/{model_name}/{model_version}"

model = mlflow.sklearn.load_model(model_uri)
model

LogisticRegression(solver='newton-cg')

In [38]:
model_uri


'models:/Iris_LogisticRegression_Model/latest'

In [39]:
y_pred_new = model.predict(X_test)

In [40]:
y_pred_new

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])